In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor
from sklearn.linear_model import Lasso, LinearRegression

'Quality of Life Index\nSafety Index\nHealth Care Index\nCost of Living Index\nProperty Price to Income Ratio\nTraffic Commute Time Index\npop_thou\nPercent Fertile\nchrstpct\njudpct\nislmpct\nbudpct\nzorpct\nbahpct\nanmpct\nnonpct\nothrpct\nAvgTemperature\npct_lt_sec\npct_some_sec\npct_some_ter\nOC\nAS\nEU\nSA\nNA\nAF\n'

In [14]:
f = open('.//Output//features.csv','r')
features = f.read()
features = features.split('\n')
f.close()
pd.read_csv('.//Output//X_train.csv',names = features)

,Quality of Life Index,Safety Index,Health Care Index,Cost of Living Index,Property Price to Income Ratio,Traffic Commute Time Index,pop_thou,Percent Fertile,chrstpct,judpct,...,pct_lt_sec,pct_some_sec,pct_some_ter,OC,AS,EU,SA,NA,AF,
0,121.535000,62.733333,64.129444,65.378333,10.167778,23.196667,743.0,45.039317,1.0,0.0,...,0.210,0.420,0.220,0.0,0.0,1.0,0.0,0.0,0.0,NaN
1,93.572778,58.805556,69.934444,26.858889,13.813889,45.480556,9884.0,53.945344,0.0,0.0,...,0.285,0.260,0.095,0.0,1.0,0.0,0.0,0.0,0.0,NaN
2,147.310000,92.580000,79.800000,32.460000,22.760000,28.060000,4552.0,52.973106,0.0,0.0,...,0.210,0.450,0.105,0.0,1.0,0.0,0.0,0.0,0.0,NaN
3,90.202857,71.637143,72.438571,33.474286,26.511429,29.608571,1627.0,52.493163,0.0,0.0,...,0.210,0.320,0.315,0.0,1.0,0.0,0.0,0.0,0.0,NaN
4,150.631667,41.686667,73.760000,67.081667,7.566667,33.895000,2518.0,45.680611,1.0,0.0,...,0.205,0.380,0.280,0.0,0.0,1.0,0.0,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,142.956667,66.806667,68.332222,58.040556,13.957778,36.480556,2897.0,44.651111,1.0,0.0,...,0.250,0.235,0.135,0.0,0.0,1.0,0.0,0.0,0.0,NaN
111,127.530000,30.836667,61.575000,71.053333,4.783333,38.123333,2466.0,46.136244,1.0,1.0,...,0.075,0.450,0.315,0.0,0.0,0.0,0.0,1.0,0.0,NaN
112,93.790000,33.806000,60.034000,41.854000,20.658000,46.661000,5698.0,54.596549,1.0,0.0,...,0.195,0.305,0.105,0.0,0.0,0.0,1.0,0.0,0.0,NaN
113,183.260556,55.256667,75.187778,94.965556,6.814444,36.772778,1865.0,47.940359,1.0,0.0,...,0.075,0.440,0.330,1.0,0.0,0.0,0.0,0.0,0.0,NaN
114,137.725000,61.980833,59.754167,51.975833,10.280000,31.496667,622.0,44.341317,1.0,0.0,...,0.025,0.470,0.330,0.0,0.0,1.0,0.0,0.0,0.0,NaN

<h3> Simple Linear Model </h3>

In [ ]:
lr_model = LinearRegression()